// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoMyY5VEtF2-1c4ywc2VOCyaqHlrdXVEg',
    appId: '1:378625854578:web:53d75240b73c66996f06eb',
    messagingSenderId: '378625854578',
    projectId: 'sonos-dialoger',
    authDomain: 'sonos-dialoger.firebaseapp.com',
    storageBucket: 'sonos-dialoger.firebasestorage.app',
    measurementId: 'G-BM5H0HQ8BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwb-eMdEeN8iS7RJEDT5S3G8j-c0ceRPU',
    appId: '1:378625854578:android:13469522061972376f06eb',
    messagingSenderId: '378625854578',
    projectId: 'sonos-dialoger',
    storageBucket: 'sonos-dialoger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCKLIrotNeJH5yPGW1Wa7VuVCYvhuAsN4',
    appId: '1:378625854578:ios:e527320ce22bf2bc6f06eb',
    messagingSenderId: '378625854578',
    projectId: 'sonos-dialoger',
    storageBucket: 'sonos-dialoger.firebasestorage.app',
    iosBundleId: 'ch.flavianz.sonosdialoger.sonosDialoger',
  );

}